[DiscoverySelectors] Add selectClass()/selectMethod() variants that take a classloader
junit-team/junit5 pull request #2107
Opened 2019-11-20 07:24 UTC by kriegfrj

This is a sample implementation of #1987.

It probably needs a bit of javadoc tidy-up, but before I invested too much time on that I wanted approval/feedback from the core team for the basic concept and the way I've implemented it.

Note that the first commit is shared in common with #2106.

2019-11-20 08:19 UTC, juliette-derancourt commented
Tentatively slated for 5.6 M2 solely for the purpose of *team discussion*

2019-11-20 09:35 UTC, marcphilipp commented
@kriegfrj Why is this better than `selectClass(classLoader.loadClass(className))`?

2019-11-20 12:18 UTC, kriegfrj commented
A fair question...

Perhaps, for similar reasons that selectClass(className) is better than selectClass(ClassLoaderUtils.getDefaultClassLoader().loadClass(className)), maybe?

Aside from being slightly more compact, it also:

1. Loads the class lazily (selector might get filtered before even needing to load the class),
2. Handles the.possible ClassNotFoundException and wraps it in a PreconditionViolationException.

But I'm happy if you guys decide otherwise.

2023-05-09 17:51 UTC, sbrannen commented
Hi @kriegfrj,

It looks like you're almost done with this PR (rebased on `main` and updated). 👍

So, it appears that only an entry in the release notes is missing.

Do you think you'll have time to finish this PR this week?

If not, someone in the team can take merge the PR and add an entry in the release notes.

Please just let us know about your availability for completing this issue.

Thanks!

2023-05-09 17:56 UTC, sbrannen requested changes
Whenever we introduce an overloaded constructor or method, we do our best to append _optional_ arguments to the formal parameter list instead of prepending them.

This aligns with conventional best practices for API design.

In light of that, please modify all constructors/methods in this PR to accept the `ClassLoader` last in the formal parameter list (unless there is a compelling reason not to do so).

Thanks

2023-05-10 06:54 UTC, kriegfrj commented
> Whenever we introduce an overloaded constructor or method, we do our best to append _optional_ arguments to the formal parameter list instead of prepending them.
> 
> This aligns with conventional best practices for API design.
> 
> In light of that, please modify all constructors/methods in this PR to accept the `ClassLoader` last in the formal parameter list (unless there is a compelling reason not to do so).
>

I think the reason I put them first (it's been a while!) was that, from a domain perspective, all the other argument lists go from least specific selector segment to most specific (eg, (class, method) or (class, method, parameters) ). In keeping with that style seemed to make the most sense to put the class loader first.

I started putting it last, and realised that it causes a source-level compatibility as some of the tests started to fail to compile due to the ambiguous overloads when supplied with a `null` parameter (this may also be part of the reason I put them first). Having looked at it though, I think in practice that this will be ok because the preconditions all insist that the `String` arguments are non-null, so there should be no existing code out in the wild that could run afoul of this newly-introduced source ambiguity. So I think in practice only the test cases that are testing the preconditions (attempting to pass in a `null`) are affected.

I've also updated the release notes.

I also realised that, since I submitted the original PR, we also have the `NestedClassSelector` and `NestedMethodSelector` which might need similar treatment... I'm not sure if I'll have time for that too.

2023-05-12 14:46 UTC, sbrannen commented
Thanks for making the requested changes and updating the release notes. 👍 

> I also realised that, since I submitted the original PR, we also have the `NestedClassSelector` and `NestedMethodSelector` which might need similar treatment... I'm not sure if I'll have time for that too.

Good catch.

I opened #3298 to track that.

2023-05-12 15:06 UTC, sbrannen approved these changes
I think this PR looks good now.

I'll make any additional changes after merging.

2023-05-12 15:09 UTC, merged

2023-05-12 19:00 UTC, sbrannen commented
This has been merged into `main` in c12634cbc65b9da528681cf3abc4b79814a3656e and revised in 142476c62c7c0e00e8b84a890a5a1319826b7cdf.

Thanks