Feature/color customization (console launcher)
junit-team/junit5 pull request #2478
Opened 2020-11-21 22:39 UTC by nmck257

## Overview

Resolving feature #985 .

This PR adds two new command line options, `--color-palette` and `--single-color`. The former accepts a properties file to override any and all ANSI color styling, and the latter provides a built-in single-color style.

Default behaviors/colors are unchanged.

Implementation note: previously, the `Color` enum contained both raw ANSI color codes and also public constants which mapped relevant styles (successful, failed, etc.) to colors. Those two concerns have been split. The `Color` enum has been refactored to `Style`, and Styles are mapped to colors / ANSI text attributes in the `ColorPalette` class. Most `disableAnsiColor` logic is now inside the `ColorPalette` concept as well.

Open question -- haven't done a PR here before -- do these changes warrant Javadoc / User Guide updates as described in the Definition of Done? 

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [X] There are no TODOs left in the code
- [X] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [X] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [X] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

2020-12-02 23:52 UTC, nmck257 commented
Hi @sormuras - any update on a review for this?

2021-07-26 02:37 UTC, nmck257 commented
Hey @sormuras, @juliette-derancourt,
I've refreshed this PR (resolved merge conflict, updated copyright year, squashed my commits) -- any interest in approving the workflows and/or doing a review?

2021-07-26 10:38 UTC, sbrannen commented
> any interest in approving the workflows and/or doing a review?

I approved the workflows and added the `new` label so that the team will discuss it.

2021-12-17 11:51 UTC, marcphilipp requested changes

2021-12-17 11:51 UTC, marcphilipp commented on junit-platform-console/src/main/java/org/junit/platform/console/tasks/Style.java
> + */
```suggestion
/**
 * @since 1.9
 */
```

2021-12-17 11:51 UTC, marcphilipp commented on junit-platform-console/src/main/java/org/junit/platform/console/tasks/ColorPalette.java
> +		this(openReader(path));
This reader should be closed.

2022-02-16 21:36 UTC, nmck257 commented
@marcphilipp - FYI, refreshed PR for new copyright year. The changes which you previously requested are also complete.

2022-03-21 09:06 UTC, sormuras approved these changes
With an addition to the 5.9-M1 release notes in section "JUnit Platform" - "New Features and Improvements", this PR looks good to me.

2022-03-21 13:22 UTC, nmck257 commented
@sormuras - great - let me know if I'm accountable to write that release note, and if so, where (first PR here).
@marcphilipp - I believe you need to sign off on your requested changes, as well.

2022-04-08 10:17 UTC, marcphilipp approved these changes

2022-04-08 11:10 UTC, merged

2022-04-08 11:11 UTC, sormuras commented
Thanks for your work on this PR and your patience, @nmck257!