Fix code so that rows in @CsvSource can start with the number sign (#)
junit-team/junit5 pull request #2528
Opened 2021-01-13 13:39 UTC by ZeroOne3010

Issue: #2527

## Overview

This change relates to the `@CsvSource` annotation and how its rows are parsed. The underlying library supports comments, by default with the number sign (#), and the support for them was left enabled for the `@CsvSource`. This does not make sense in that the tests just throw a `PreconditionViolationException` in case the number sign is used at the start of a row. So, this pull request disables comment processing for  `@CsvSource` but leaves it enabled for  `@CsvFileSource`, as not to disturb existing, documented functionality.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- ✓ There are no TODOs left in the code
- (N/A) Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- ✓ [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- ✓ Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- (N/A) Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- (How to do this??) Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- (As far as I know) All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

2021-01-13 14:47 UTC, sbrannen commented
Tentatively slated for 5.8 M1 for _team discussion_

2021-01-15 11:46 UTC, marcphilipp commented
**Team decision:** Follow the proposal.

2021-01-15 11:47 UTC, marcphilipp requested changes
Looks good! Could you please add an entry to the 5.8 M1 release notes in the Jupiter section?

2021-01-15 13:58 UTC, ZeroOne3010 commented
Thanks @marcphilipp! I've amended the release notes now. ✔️

2021-01-15 19:49 UTC, marcphilipp approved these changes
Thanks! 👍

2021-01-15 19:51 UTC, merged