Validate packages against every Java keyword
junit-team/junit5 pull request #2571
Opened 2021-03-16 16:26 UTC by paplorinc

Fixes: https://github.com/junit-team/junit5/issues/2570

2021-03-17 17:06 UTC, Cu2y approved these changes

2021-03-18 09:27 UTC, marcphilipp requested changes

2021-03-18 09:27 UTC, marcphilipp commented on junit-platform-commons/src/main/java/org/junit/platform/commons/util/PackageUtils.java
> +		 * */
```suggestion
		/*
		 * Based on https://docs.oracle.com/javase/specs/jls/se16/html/jls-3.html#jls-Identifier
		 */
```

2021-03-19 12:41 UTC, marcphilipp requested changes
Sorry, stating that `PackageUtils` should be removed was premature. What I meant was to remove `PackageUtils.assertPackageNameIsValid`.

2021-03-19 12:41 UTC, marcphilipp commented on junit-platform-commons/src/main/java/org/junit/platform/commons/util/ClasspathScanner.java
>  		Preconditions.notNull(classFilter, "classFilter must not be null");
```suggestion
		Preconditions.condition(DEFAULT_PACKAGE_NAME.equals(basePackageName) || isNotBlank(basePackageName), "basePackageName must not be blank");
		Preconditions.notNull(classFilter, "classFilter must not be null");
```

2021-03-19 16:53 UTC, marcphilipp approved these changes

2021-03-19 16:57 UTC, merged

2021-03-19 16:57 UTC, marcphilipp commented
Thanks, @paplorinc! 👍