Add Named.named as a more static import friendly alternative to Named.of
junit-team/junit5 pull request #2591
Opened 2021-04-09 11:45 UTC by helpermethod

Issue: #2587

## Overview

This PR adds Named.named as a more static import friendly alternative to Named.of.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

2021-04-09 14:04 UTC, helpermethod commented
@sbrannen I've updated the JavaDocs and added a basic test.

2021-04-09 14:11 UTC, sbrannen commented
Related to #1419

2021-04-09 14:16 UTC, sbrannen requested changes
This PR looks good. Just a few requests for minor modifications:

- add the missing `@since` tag to the class-level Javadoc for `Named`
- make the requested Javadoc formatting changes
- add an entry to the release notes analogous to https://github.com/junit-team/junit5/commit/59fc540687cde4dc9450e44b748e42f6b67e28c2#diff-fa8f51b8f6e83a043f782cebd4150af1a1c7587ddb8bbcfae67d12e9cd19f2d2R51-R52

Thanks

2021-04-09 14:16 UTC, sbrannen commented on junit-jupiter-api/src/main/java/org/junit/jupiter/api/Named.java
> +	 * Factory method for creating an instance of {@code Named} based on a {@code name} and a {@code payload}
Please wrap Javadoc around 80 characters and end the statement with a period.

2021-04-09 14:16 UTC, sbrannen commented on junit-jupiter-api/src/main/java/org/junit/jupiter/api/Named.java
> +	 * Factory method for creating an instance of {@code Named} based on a {@code name} and a {@code payload}
Please wrap Javadoc around 80 characters and end the statement with a period.

2021-04-09 19:24 UTC, helpermethod commented
@sbrannen Applied the suggested changes, thanks for reviewing!

2021-04-12 15:13 UTC, sbrannen commented
> @sbrannen Applied the suggested changes, thanks for reviewing!

Thanks for making the changes. I'll make a final review in the coming days.

2021-04-16 12:45 UTC, sbrannen approved these changes

2021-04-16 16:21 UTC, closed without merging

2021-04-16 16:22 UTC, sbrannen commented
This has been merged into `main` in 727f51d316f49074c7fb82e7f1136bfbb42e5a9a and revised in ce567289b26f3e9c2591b1ab2444f7ae3f4d28a6.

Thanks