Add FreeBSD and OpenBSD to OS condition
junit-team/junit5 pull request #2821
Opened 2022-02-05 07:34 UTC by dbwiddis

## Overview

My cross-platform project supports FreeBSD and OpenBSD and I'd like to be able to use the annotations rather than conditionals.  I followed the same format used for AIX.

I see some additional tests in [org/junit/jupiter/api/condition/EnabledOnOsConditionTests.java](https://github.com/junit-team/junit5/blob/e69243ae0f3c68f07d075ac3901c98c375d040f0/junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledOnOsConditionTests.java) and [org/junit/jupiter/api/condition/EnabledOnOsConditionTests.java](https://github.com/junit-team/junit5/blob/e69243ae0f3c68f07d075ac3901c98c375d040f0/junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledOnOsConditionTests.java) that were not updated with the AIX addition so I did not (yet) add these OS's.  Let me know if you'd like me to update these with all three new additions.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

2022-02-05 07:38 UTC, sormuras approved these changes
Additions look good to me.

2022-02-05 07:44 UTC, sormuras commented
Please, add a line to the release notes, like it was done by Sam in the AIX commit: https://github.com/junit-team/junit5/commit/f0808b798a43aaa552402d5dcc76a330c1a3d320

> I see some additional tests in [org/junit/jupiter/api/condition/EnabledOnOsConditionTests.java](https://github.com/junit-team/junit5/blob/e69243ae0f3c68f07d075ac3901c98c375d040f0/junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledOnOsConditionTests.java) and [junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledOnOsConditionTests.java](https://github.com/junit-team/junit5/blob/e69243ae0f3c68f07d075ac3901c98c375d040f0/junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledOnOsConditionTests.java) that were not updated with the AIX addition so I did not (yet) add these OS's. Let me know if you'd like me to update these with all three new additions.

Adding missing tests is always appreciated. We won't stop you.

2022-02-05 13:39 UTC, sbrannen requested changes
I agree with @sormuras.

This looks good. Thanks for adding this.

And please do add an entry in the release notes as well as the missing tests.

2022-02-05 20:26 UTC, dbwiddis commented
Updates complete.

2022-02-05 20:50 UTC, sormuras requested changes
Please run `./gradlew spotlessApply` to fix format violations.

2022-02-05 21:03 UTC, dbwiddis commented
Looks like some parentheses went astray. Fixing.

2022-02-05 21:05 UTC, sormuras commented
Here are some: `){(}]}` ... pick as many as you need. 🙂

Btw. no need to force-push. We usually squash commits before merging.

2022-02-05 22:03 UTC, sormuras approved these changes

2022-02-06 14:47 UTC, sbrannen approved these changes
Looks good.

Thanks for making the changes.

2022-02-06 15:13 UTC, closed without merging

2022-02-06 15:14 UTC, sbrannen commented
This has been merged into `main`.

Thanks for making your first contribution to JUnit! 👍