Limit the number of concurrently executing tests via a property
junit-team/junit5 pull request #3044
Opened 2022-09-24 12:58 UTC by mpkorstanje

## Overview

JUnit Jupiter (and The JUnit Platform) now support limiting the maximum number of concurrently executing tests via the `junit.jupiter.execution.parallel.config.fixed.max-pool-size` property.

With Java 9+ the `ForkJoinPool` used by JUnit can be configured with a maximum pool size. While the number of concurrently executing tests may exceed the configured parallelism when tests become blocked, it will not exceed the maximum pool size.

With the following configuration:

```properties
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.config.strategy=fixed
junit.jupiter.execution.parallel.mode.default=concurrent
junit.jupiter.execution.parallel.config.fixed.parallelism=2
```

This example will report between 2-5 tests running concurrently.

```java
class ExampleTest {

    private static final AtomicInteger running = new AtomicInteger();

    @BeforeEach
    void increment() {
        System.out.println("Running " + running.incrementAndGet());
    }

    @AfterEach
    void decrement() {
        running.decrementAndGet();
    }

    static IntStream numbers() {
        return IntStream.range(0, 1000);
    }

    @ParameterizedTest
    @MethodSource("numbers")
    void test(int i) throws ExecutionException, InterruptedException {
        Runnable sleep = () -> {
            try {
                Thread.sleep(600);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        };
        ForkJoinPool.commonPool().submit(sleep).get();
    }
}
```

By also configuring the `max-pool-size` we can ensure the concurrently executing test does not exceed the configured 2.

```properties
junit.jupiter.execution.parallel.config.fixed.max-pool-size=2
```

Additionally, because the `ForkJoinPool` will by default reject tasks that would exceed the maximum pool size the
`junit.jupiter.execution.parallel.config.fixed.saturate` property has been added and will default to `true`. There appears to be no reason to ever set this `false` but it is there should someone depend on the old behaviour.

These changes were intentionally not made to the `dynamic` strategy to limit the scope of this pull request. While I can reasonably predict what behaviour users of the `fixed` strategy might expect, I can not say the same about the `dynamic` strategy.

Fixes: #2545
Fixes: #1858
Fixes: #3026

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

2022-09-24 13:28 UTC, mpkorstanje commented
@marcphilipp To update the changelog I'd need to know which mile stone would go into.

2022-09-24 13:33 UTC, sbrannen commented
> To update the changelog I'd need to know which milestone would go into.

I just created [5.10 M1](https://github.com/junit-team/junit5/milestone/65). So feel free to use that.

If it ends up landing in a different milestone, we'll move the change log entry accordingly.

2022-09-24 13:35 UTC, sbrannen commented
Note, however, that there is currently no file for the 5.10 M1 release notes.

So, you'll need to follow the instructions in `release-notes-TEMPLATE.adoc`.

If that seems too cumbersome, a core committer can create the new file for you.

2022-10-16 09:41 UTC, mpkorstanje commented
Explanation of why this fixes the listed issues:

For #2545:

While the proposed solution involves a `ForkJoinWorkerThreadFactory` the underlying root cause follows from the inability to saturate the fork join pool. This was fixed by #2792 and can be achieved through a custom parallel strategy. This PR simplifies the process and should for this specific use case remove the need for more complicated solutions.

For #1858:

The root cause was explained in https://github.com/junit-team/junit5/issues/1858#issuecomment-482189645. When a test puts its executing thread to sleep, JUnit will start another test to keep up the desired parallism. However as explained in https://github.com/junit-team/junit5/issues/1858#issuecomment-482609294 when using Selenium threads are commonly put to sleep and so it is desirable to limit the maximum pool size to limit the maximum number of web drivers created.

This too was fixed by #2792 and can be achieved through a custom parallel strategy. This PR simplifies the process and should for this specific use case remove the need for more complicated solutions.

For #3026:

Essentially this issues requests a configuration parameter to limit the maximum pool size and allow saturation. Removing the need to create a custom class for this very common scenario,

2022-10-17 15:50 UTC, OPeyrusse commented
Even though I am not a member of this repository, I would like to warn you that what you did will not work with people also using `ForkJoinPool`.
I explained in [this comment](https://github.com/junit-team/junit5/issues/1858#issuecomment-1281081183) on #1858 how a single thread can end up running 40+ tests "concurrently". By concurrently, I mean that 40+ tests can report as having start, before any can complete.
If this is a use case that you plan to support with this PR, I would gladly assist you in designing a test case that reproduce the issue. Don't hesitate to ping me if you want.

2022-10-17 17:24 UTC, mpkorstanje commented
Thanks for the heads-up! I didn't see that specific problem explicitly mentioned in the issues before so I left it out of scope.

I reckon the current PR can still be salvaged by fixing the wording. 😅

2022-10-18 07:21 UTC, OPeyrusse commented
@mpkorstanje Do you want me to create a special test and open an issue for that particular problem?

2022-10-21 13:26 UTC, marcphilipp approved these changes
Looks good except for a few minor documentation things.

2022-10-21 13:26 UTC, marcphilipp commented on documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
> +| a positive integer, must not be smaller then `junit.jupiter.execution.parallel.config.fixed.parallelism`
```suggestion
| a positive integer, must not be less than `junit.jupiter.execution.parallel.config.fixed.parallelism`
```

2022-10-21 13:26 UTC, marcphilipp commented on junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/Constants.java
> +	 * <p>Value must be an integer and larger or equal to
```suggestion
	 * <p>Value must be an integer and greater than or equal to
```

2022-10-21 13:26 UTC, marcphilipp commented on junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/DefaultParallelExecutionConfigurationStrategy.java
> +	 * <p>Value must be an integer and larger or equal to
```suggestion
	 *
	 * <p>Value must be an integer and greater than or equal to
```

2022-10-21 13:26 UTC, marcphilipp commented on junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/DefaultParallelExecutionConfigurationStrategy.java
> +	 * <p>When set to {@code false} the underlying fork join pool will reject
```suggestion
	 *
	 * <p>When set to {@code false} the underlying fork join pool will reject
```

2022-10-21 14:34 UTC, mpkorstanje commented
@OPeyrusse yes, please do. I can't promise or commit to solving it. But perhaps someone can.

2022-10-25 13:06 UTC, mpkorstanje commented
I think this is what @OPeyrusse had in mind. The code below will report between 2-6 active tests as the `.join()` call will end up starting other tests. The number of active threads however does not exceed 2. 

I've updated the documentation to say concurrent "threads" instead of "tests".

```java
class ExampleTest {
    private static final Runnable sleep = () -> {
        try {
            Thread.sleep(600);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    };

    private static final AtomicInteger running = new AtomicInteger();

    @BeforeEach
    void increment() {
        System.out.println("Running " + running.incrementAndGet());
    }

    @AfterEach
    void decrement() {
        running.decrementAndGet();
    }

    static IntStream numbers() {
        return IntStream.range(0, 1000);
    }

    @ParameterizedTest
    @MethodSource("numbers")
    void test(int i) {
        ForkJoinPool.commonPool()
                .submit(sleep)
                .join();
    }

    @ParameterizedTest
    @MethodSource("numbers")
    void test2(int i) {
        ForkJoinPool.commonPool()
                .submit(sleep)
                .join();
    }
}
```

2022-10-25 13:12 UTC, mpkorstanje commented
@marcphilipp good to go.

2022-10-26 09:28 UTC, sbrannen requested changes
Thanks for the PR!

I've requested some minor changes to the documentation.

2022-10-26 09:28 UTC, sbrannen commented on documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc
> +* Support limiting the max-pool-size for parallel execution via a property
```suggestion
* Support for limiting the `max-pool-size` for parallel execution via a configuration parameter
```

2022-10-26 09:28 UTC, sbrannen commented on documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc
> +  default
```suggestion
* The `fixed` parallel execution strategy now allows the thread pool to be saturated by
  default.
```

2022-10-26 09:28 UTC, sbrannen commented on documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc
> +==== New Features and Improvements
This document now contains 2 `New Features and Improvements` sections.

Please remove the unused section.

2022-10-26 09:28 UTC, sbrannen commented on documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
> +| Desired maximum pool size of the underlying fork join pool for the ```fixed```
```suggestion
| Desired maximum pool size of the underlying fork-join pool for the ```fixed```
```

2022-10-26 09:28 UTC, sbrannen commented on junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/Constants.java
> +	 * pool-size would be exceeded.
```suggestion
	 * <p>When set to {@code false} the underlying fork-join pool will reject
	 * additional tasks if all available workers are busy and the maximum
	 * pool-size would be exceeded.
```

2022-10-26 09:28 UTC, sbrannen commented on junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/DefaultParallelExecutionConfigurationStrategy.java
> +	 * fork join pool for the {@link #FIXED} configuration strategy.
```suggestion
	 * fork-join pool for the {@link #FIXED} configuration strategy.
```

2022-10-26 09:28 UTC, sbrannen commented on junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/DefaultParallelExecutionConfigurationStrategy.java
> +	 * <p>When set to {@code false} the underlying fork join pool will reject
```suggestion
	 * <p>When set to {@code false} the underlying fork-join pool will reject
```

2022-10-26 09:28 UTC, sbrannen commented on junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/DefaultParallelExecutionConfigurationStrategy.java
> +	 * additional tasks when all available workers are busy and the maximum
```suggestion
	 * additional tasks if all available workers are busy and the maximum
```

2022-10-26 11:29 UTC, mpkorstanje commented
Changes applied! 

For fixing small mistakes and typos please do feel free to push directly to my branch.

2022-10-26 11:36 UTC, sbrannen approved these changes

2022-12-30 14:49 UTC, merged