Document that calls to `TestExecutionListener` are executed synchronously
junit-team/junit5 pull request #3092
Opened 2022-11-14 18:20 UTC by juliette-derancourt

Resolves #3061

2022-11-14 18:21 UTC, juliette-derancourt commented on documentation/src/docs/asciidoc/user-guide/advanced-topics/launcher-api.adoc
> +Test case execution won't start before all `executionStarted` calls have returned.
@jlink @marcphilipp Would that be the right place for this?

2022-12-30 15:02 UTC, marcphilipp requested changes

2022-12-30 15:02 UTC, marcphilipp commented on documentation/src/docs/asciidoc/user-guide/advanced-topics/launcher-api.adoc
> +NOTE: `TestExecutionListener` are called sequentially in registration order.
```suggestion
NOTE: All `TestExecutionListener` methods are called sequentially. Methods for start
events are called in registration order while methods for finish events are called in
reverse order.
```

2022-12-30 15:02 UTC, marcphilipp commented on junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestExecutionListener.java
> + * calls have returned.
```suggestion
 * <p>All {@code TestExecutionListener} methods are called sequentially. Methods
 * for start events are called in registration order while methods for finish
 * events are called in reverse order. Test case execution won't start before
 * all {@link #executionStarted(TestIdentifier)} calls have returned.
```

2023-01-10 10:56 UTC, marcphilipp approved these changes

2023-01-10 14:46 UTC, merged