Introduce new `@MethodSource` syntax to differentiate overloaded local factory methods
junit-team/junit5 pull request #3101
Opened 2022-12-04 16:22 UTC by juliette-derancourt

## Overview

Resolves #3080 

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

2022-12-11 13:35 UTC, marcphilipp requested changes

2022-12-11 13:35 UTC, marcphilipp commented on junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/MethodArgumentsProvider.java
> +		String[] methodParts = ReflectionUtils.parseSimpleMethodName(factoryMethodName);
I think we should avoid parsing the method name again here (in addition to in `findFactoryMethodCandidates`) and instead only do so once and pass it as an argument to both methods.

2022-12-30 12:48 UTC, marcphilipp approved these changes

2023-01-08 15:26 UTC, sbrannen approved these changes
This looks good! Thanks, @juliette-derancourt.

I'll merge it into `main` and make a final pass in my IDE.

2023-01-08 17:44 UTC, closed without merging