Update @TestInstance javadoc with a new use case
junit-team/junit5 pull request #3219
Opened 2023-03-31 18:49 UTC by mahozad

## Overview

Related Stack Overflow post: [What use is @TestInstance annotation in JUnit 5?](https://stackoverflow.com/a/66185596/8583692)

Add another use case for `TestInstace.PER_CLASS` in Kotlin, which is, using regular simple class methods as the argument producer for `@MethodSource` (which is used for parameterized tests):

```kotlin
@ParameterizedTest
@MethodSource("generateStrings")
fun `Test strings`(argument: String) {
    check(argument.isNotEmpty())
}

private fun generateStrings() = listOf(
    "java",
    "kotlin"
)
```

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

2023-04-01 13:21 UTC, sbrannen requested changes
Please update the [User Guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-instance-lifecycle) in a similar fashion.

2023-04-02 13:36 UTC, sbrannen approved these changes
Thanks for updating the user guide as well.

2023-04-02 13:38 UTC, merged

2023-04-02 13:39 UTC, sbrannen commented
This has been merged into `main`.

Thanks

2023-04-02 14:57 UTC, mahozad commented
Thanks for merging.