Make @TempDir meta annotation capable
junit-team/junit5 pull request #3313
Opened 2023-05-15 18:57 UTC by marschall

Add ANNOTATION_TYPE as a target to @TempDir to allow it to be used in meta annotations.

Issue: #3311

## Overview

Add ANNOTATION_TYPE as a target to @TempDir to allow it to be used in meta annotations.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

2023-05-16 08:13 UTC, sbrannen requested changes
I've requested a few minor changes.

A brief note in the User Guide stating that `@TempDir` can be used as a meta-annotation would be helpful, perhaps even with an example.

Please also add an entry in the release notes, or if you find that too cumbersome (since the release notes file does not yet exist) just let us know, and we'll add the release note entry after merging.

2023-05-16 08:13 UTC, sbrannen commented on junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryMetaAnnotationTests.java
> + * Integration tests for the use of {@link TempDir} in a meta annotation.
```suggestion
 * Integration tests for the use of {@link TempDir} as a meta-annotation.
```

2023-05-16 08:13 UTC, sbrannen commented on junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryMetaAnnotationTests.java
> +@DisplayName("@TempDir as a meta annotation")
```suggestion
@DisplayName("@TempDir as a meta-annotation")
```

2023-05-27 16:21 UTC, sbrannen approved these changes
This looks good now.

Thanks! 👍 

p.s. there's a slight issue with the terminology regarding "meta-annotation" vs. "composed annotation", but I'll address that after merging the PR.

2023-05-27 16:34 UTC, closed without merging

2023-05-27 16:36 UTC, sbrannen commented
This has been merged into `main` in 6ae599b8865dbd16cd2ecd9e8ebb52937bea3733 and revised in e205ccd802038c24a50a1453765ba8c4c31c41c7.

Thanks

2023-05-29 13:32 UTC, marschall commented
Awesome, thanks a lot. Looking forward to RC1