Revise stacktrace pruning
junit-team/junit5 pull request #3364
Opened 2023-06-19 16:14 UTC by juliette-derancourt

## Overview

Resolves #3299

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

2023-06-20 09:02 UTC, sbrannen requested changes
I've requested a few minor changes and will hopefully find time to perform a more thorough review after the PR has been updated.

2023-06-20 09:02 UTC, sbrannen commented on platform-tests/src/test/java/org/junit/platform/commons/util/ExceptionUtilsTests.java
> +	void pruneStackTraceOfCallsFromSpecificPackage(String shouldBePruned) {
Is there a concrete need to throw and catch these exceptions?

If not, just rely on the fact that `fillInStackTrace()` is called by the exceptions constructor (technically in `java.lang.Throwable.Throwable(String)`).

2023-06-20 09:02 UTC, sbrannen commented on platform-tests/src/test/java/org/junit/platform/commons/util/ExceptionUtilsTests.java
> +			pruneStackTrace(e, Collections.emptyList());
In tests, feel free to use `List.of()` instead of `Collections.emptyList()`.

2023-06-22 09:14 UTC, sbrannen approved these changes

2023-06-25 06:38 UTC, marcphilipp requested changes

2023-06-25 06:38 UTC, marcphilipp commented on junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java
> +				.excludeMatchingClassNames(STACK_TRACE_ELEMENTS_TO_EXCLUDE);
I think we should extract this into a constant.

2023-06-25 06:38 UTC, marcphilipp commented on junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java
> +		return Stream.of(testDescriptor.getSource(), testDescriptor.getParent().flatMap(TestDescriptor::getSource)) //
I think we should do this up to the engine descriptor. For example, to handle an exception thrown from a top-level `@BeforeEach` method with multiple levels of `@Nested` classes.

2023-06-26 05:26 UTC, marcphilipp approved these changes

2023-06-27 06:00 UTC, sormuras approved these changes

2023-06-28 18:41 UTC, merged