Feat redirect stderr and stdout
junit-team/junit5 pull request #3637
Opened 2024-01-14 13:17 UTC by mobounya

## Overview

Add new CLI options `--redirect-stdout` and `--redirect-stderr` to redirect stdout and stderr respectively to a file,
if both are set to the same file, stdout and stderr will be merged using the configuration parameter
`CAPTURE_MERGED_STANDARD_STREAMS_PROPERTY_NAME` and captured from stdout key `STDOUT_REPORT_ENTRY_KEY` in a new TestExecutionListener : `RedirectStdoutAndStderrListener`

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

2024-01-14 14:56 UTC, ahmedelbahri commented
khaari

2024-10-23 09:46 UTC, marcphilipp requested changes
I don't think we should implement this new `ConsoleLauncher` feature based on the report entries. Instead, the `ConsoleLauncher` should replace `System.out` and `System.err` prior to calling `Launcher.execute` with `PrintStreams` writing to files (or the same file). This would allow to configure capturing the output as report entries separately.

2024-10-23 09:46 UTC, marcphilipp commented on documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-M1.adoc
> +* New optional CLI options `--redirect-stdout` and `--redirect-stderr` to redirect stdout and stderr outputs to a file.
This needs to go to the release notes of 5.12.0-M1 now

2024-10-23 09:46 UTC, marcphilipp commented on documentation/src/docs/asciidoc/user-guide/running-tests.adoc
> +<<running-tests-config-params, configuration parameter>> to `true`. And since version 5.11
```suggestion
<<running-tests-config-params, configuration parameter>> to `true`. And since version 1.12
```

2024-10-23 09:46 UTC, marcphilipp commented on junit-platform-console/src/main/java/org/junit/platform/console/options/TestConsoleOutputOptions.java
> +	@API(status = INTERNAL, since = "5.11")
```suggestion
	@API(status = INTERNAL, since = "5.12")
```
same below

2024-10-23 09:46 UTC, marcphilipp commented on junit-platform-console/src/main/java/org/junit/platform/console/options/TestConsoleOutputOptionsMixin.java
> +
We're only maintaining this kind of options for backwards compatibility (we switched to option parsers at some point) but we shouldn't introduce them for new options.

```suggestion
```

2024-10-23 09:46 UTC, marcphilipp commented on junit-platform-console/src/main/java/org/junit/platform/console/options/TestConsoleOutputOptionsMixin.java
> +
```suggestion
```

2024-10-23 09:46 UTC, marcphilipp commented on junit-platform-console/src/main/java/org/junit/platform/console/options/TestConsoleOutputOptionsMixin.java
> +			result.setStderrPath(choose(stderr, stderr2, null));
```suggestion
			result.setStdoutPath(stdout);
			result.setStderrPath(stderr);
```

2024-10-23 09:47 UTC, marcphilipp commented
@mobounya Thank you for your PR! Sorry it took us so long to review it. Are you still interested in continuing?

2024-11-22 15:42 UTC, mobounya commented
Sorry for the delay, I've been busy with work, yes I will pick this up in the weekend

2024-12-05 07:55 UTC, marcphilipp commented
@mobounya Any updates?

2025-01-27 16:42 UTC, marcphilipp commented
@mobounya Do you think you'll have time to pick this up again or should someone else take over?

2025-01-27 17:10 UTC, mobounya commented
My bad, unfortunately I am unable to continue working on this as I don't have the time, someone can take over

2025-01-28 14:06 UTC, marcphilipp commented
No worries, thanks for letting us know!

2025-02-12 07:23 UTC, marcphilipp commented
Superseded by #4311

2025-02-12 07:23 UTC, closed without merging