Support "void" in ReflectionUtils
junit-team/junit5 pull request #4049
Opened 2024-10-06 09:31 UTC by bjmi

Fix #4048

2024-10-06 09:38 UTC, marcphilipp commented
Could you please add an "integration test" demonstrating the scenario from #4048 is now supported?

2024-10-06 11:58 UTC, sbrannen requested changes
Thanks for the PR!

I would not consider `Void[]` and `Void[][]` "common types", so please remove those from the `classNameToTypeMap` cache.

2024-10-06 11:58 UTC, sbrannen commented on junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
> +			Void[].class,
```suggestion
```

2024-10-06 11:58 UTC, sbrannen commented on junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
> +			Void[][].class,
```suggestion
```

2024-10-06 13:00 UTC, bjmi commented on junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
> +			Void[][].class,
Applied.

2024-10-06 13:00 UTC, bjmi commented on junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
> +			Void[].class,
Applied.

2024-10-07 07:04 UTC, marcphilipp requested changes
> > Could you please add an "integration test" demonstrating the scenario from #4048 is now supported?
> 
> This is now implicitly tested by `DefaultArgumentConverterTests.convertsStringToClass()`. Should the newly introduced `DefaultArgumentConverterTests.IntegrationTests` still be retained?

Thanks! No, I don't think we need `DefaultArgumentConverterTests.IntegrationTests`.

Please add an entry to the 5.12.0-M1 release notes.

2024-10-07 15:56 UTC, bjmi commented
> Thanks! No, I don't think we need `DefaultArgumentConverterTests.IntegrationTests`.

Removed.
> Please add an entry to the 5.12.0-M1 release notes.

As I'm not a native speaker feel free to change the text in the release notes.

2024-10-08 08:23 UTC, marcphilipp approved these changes

2024-10-08 08:42 UTC, merged

2024-10-08 08:43 UTC, marcphilipp commented
Thanks, @bjmi! :+1: