Allow declaring exclusive resources for child nodes
junit-team/junit5 pull request #4151
Opened 2024-11-23 12:19 UTC by VladimirDmitrienko

Issue: #3102

## Overview

Allow declaring "shared resources" for _direct_ child nodes via the new `@ResourceLock(target = CHILDREN)` attribute.
 
It may improve parallelization when a test class declares a `READ` lock, but only a few methods hold a `READ_WRITE` lock.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

2024-11-23 14:11 UTC, VladimirDmitrienko commented on platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/ResourceLockAnnotationTests.java
> -	static class NestedNestedTestCase {
Forgot to delete this test case draft in the previous [PR](https://github.com/junit-team/junit5/pull/3889) 😓

2024-11-25 08:51 UTC, marcphilipp requested changes
Looks good! I only found some minor things.

2024-11-25 08:51 UTC, marcphilipp commented on junit-jupiter-api/src/main/java/org/junit/jupiter/api/parallel/ResourceLockTarget.java
> +	 *     - test methods declared in the nested class.</li>
```suggestion
	 *     - test methods and nested test classes declared in the nested class.</li>
```

2024-11-25 08:51 UTC, marcphilipp commented on junit-jupiter-api/src/main/java/org/junit/jupiter/api/parallel/ResourceLockTarget.java
> +	 *     <li>a test method - considered to have no children.</li>
This fails, right? We should document that `CHILDREN` cannot be used on methods.

2024-11-25 08:51 UTC, marcphilipp commented on documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
> +to each test method declared in this class.
```suggestion
to each test method and nested test class declared in this class.
```

2024-11-25 08:51 UTC, marcphilipp commented on documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
> +It may improve parallelization when a test class declares a `READ` lock,
```suggestion
This may improve parallelization when a test class declares a `READ` lock,
```

2024-11-25 08:51 UTC, marcphilipp commented on documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
> +doesn't have the `target = CHILDREN`. This is because the test class declares a `READ`
```suggestion
didn't have `target = CHILDREN`. This is because the test class declares a `READ`
```

2024-11-25 08:51 UTC, marcphilipp commented on documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
> +which forces the `SAME_THREAD` execution mode for all the test methods.
```suggestion
which would force the `SAME_THREAD` execution mode for all the test methods.
```

2024-11-26 08:02 UTC, marcphilipp approved these changes

2024-11-26 08:28 UTC, merged

2024-11-26 08:35 UTC, marcphilipp commented
Thank you for your contribution, @vdmitrienko! :+1: 

After merging, I noticed that the tests were in the wrong package/project so I moved them in c1a976e652e2e30bc7a8a6309bf2497ce96dbd16.

2024-11-26 09:49 UTC, vdmitrienko commented
> Thank you for your contribution, @vdmitrienko! 👍

My pleasure!

> After merging, I noticed that the tests were in the wrong package/project so I moved them in https://github.com/junit-team/junit5/commit/c1a976e652e2e30bc7a8a6309bf2497ce96dbd16.

Thank you.