Fix DiaplayNameGenerator to access enclosing type for @Nested
junit-team/junit5 pull request #4162
Opened 2024-11-28 13:59 UTC by neronsoda

This PR is supposed to resolve the Issue: #4130

## Overview

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [X] There are no TODOs left in the code
- [X] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [X] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [X] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [X] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [X] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

2024-11-28 15:21 UTC, neronsoda commented
It seems that some existing tests have been affected by the changes in adding `throw new UnsupportedOperationException`
I will keep correcting errors.
If you have any feedback, please feel free to share it.

2024-11-28 15:56 UTC, marcphilipp requested changes
The old methods of `DisplayNameGenerator` (that now throw `UnsupportedOperationException`) should neither be called nor implemented anymore.

2024-11-28 15:56 UTC, marcphilipp commented on junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DisplayNameUtils.java
>  	}
This method and the one above for nested classes should no longer be used and therefore deleted.

2024-11-30 06:31 UTC, neronsoda commented
@sbrannen 
`DisplayNameGenerationTests > indicativeSentencesGenerationInheritance() FAILED`
`Caused by:
        java.lang.UnsupportedOperationException: Implement generateDisplayNameForNestedClass(List<Class<?>>, Class<?>) instead`
This error seems to be due to using the old method throwing an exception.
I'm going to fix the relevant codes.

@marcphilipp
Thank you for the feedback.
I'm going to find all the parts that use the old method and fix it.

I'll leave a comment here if I need feedback :)

2024-12-18 11:06 UTC, marcphilipp commented
@neronsoda Any updates? Please let us know if you don't have enough time to finish this and we should take over.

2024-12-19 15:42 UTC, neronsoda commented
@marcphilipp
Hi. I've been continuing this issue, but it didn't work out well, so I've been taking a break recently.
I'm going to try to proceed again within a few days.
Is there a deadline for this issue?

2024-12-19 15:55 UTC, marcphilipp commented
We'd like to include it in 5.12 which is targeting end of January. So we should try to get this PR merged by mid-January so we'll have enough time to address the issues that depend on it afterwards.

2024-12-27 12:54 UTC, neronsoda commented
Okay, I got it. I'm continuing this issue.
I aim to solve this issue by January 8th.
I'll try to proceed as soon as possible and tell you if I think I can't.

2025-01-09 13:15 UTC, marcphilipp commented
@neronsoda Any updates?

2025-01-13 04:32 UTC, neronsoda commented
I kept trying, but I think this issue will be hard for me to solve completely.
Thank you for the opportunity, and I will try another issue again next time.
Thank you.

2025-01-13 07:09 UTC, marcphilipp commented
@neronsoda No worries! Thanks for letting us know! :+1:

2025-01-13 07:09 UTC, closed without merging

2025-01-29 14:34 UTC, sbrannen commented
- superseded by #4266