Add JRE.JAVA_25
junit-team/junit5 pull request #4181
Opened 2024-12-07 08:14 UTC by sormuras

## Overview

Add `JRE.JAVA_25` constant and JDK 25 CI build

Closes #4177

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

2024-12-08 07:19 UTC, marcphilipp requested changes

2024-12-08 07:19 UTC, marcphilipp commented on gradle/base/code-generator-model/src/main/resources/jre.yaml
> +  since: '5.12'
```suggestion
  since: '5.11.4'
```

2024-12-08 18:42 UTC, marcphilipp approved these changes

2024-12-09 10:09 UTC, sormuras reviewed
Add backticks around type and constant names

2024-12-09 10:09 UTC, sormuras commented on documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
> +* JAVA_25 has been added to the JRE enum for use with JRE-based execution conditions.
```suggestion
* `JAVA_25` has been added to the `JRE` enum for use with JRE-based execution conditions.
```

2024-12-09 10:09 UTC, sormuras commented on documentation/src/docs/asciidoc/release-notes/release-notes-5.11.4.adoc
> +* JAVA_25 has been added to the JRE enum for use with JRE-based execution conditions.
```suggestion
* `JAVA_25` has been added to the `JRE` enum for use with JRE-based execution conditions.
```

2024-12-09 10:14 UTC, marcphilipp requested changes
I don't think this should be included in the 5.12.0-M1 release notes since we're releasing 5.11.4 _before_ 5.12.0-M1 so it's reasonable to assume everything from the former is contained in the latter.

2024-12-09 10:14 UTC, merged

2024-12-09 10:17 UTC, sormuras commented
Yeah, had a similar thought, but someone who reads only the 5.12(.0) notes should get a chance to see what's new compared to the 5.11(.0) notes, not?

2024-12-09 10:20 UTC, marcphilipp commented
I don't think we've usually done that. I'm okay with keeping it, though.