Introduce from and to attributes on @EnumSource (#4185)
junit-team/junit5 pull request #4221
Opened 2024-12-24 09:50 UTC by yhkuo41

Resolves #4185.

## Overview

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

2024-12-27 19:27 UTC, CharlesLgn commented on junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EnumArgumentsProvider.java
> +		return EnumSet.range(from, to);
What happen if `from > to` or if `from == to` ?
It maybe need to be specify somewhere in the doc, and have a test on this cases

2025-01-02 10:34 UTC, marcphilipp commented on documentation/src/test/java/example/ParameterizedTestDemo.java
> +	@EnumSource(mode = EXCLUDE, from = "HOURS", to = "DAYS", names = { "HALF_DAYS" })
Changing the order of the enum in the JDK would be a breaking change which is not usually done so I think we're safe here.

2025-01-02 10:38 UTC, marcphilipp commented on junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EnumArgumentsProvider.java
> +		return EnumSet.range(from, to);
I think we should allow `from == to` (like `EnumSet.range`) but throw an error in case `from > to` with a good message.

@yhkuo41 Could you please add that?

2025-01-02 10:39 UTC, marcphilipp commented on documentation/src/test/java/example/ParameterizedTestDemo.java
> +	}
Why?

2025-01-02 10:45 UTC, marcphilipp requested changes

2025-01-02 10:45 UTC, marcphilipp commented on junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EnumSource.java
> +
Please add `@since 5.12` to the Javadoc and `@API(status = EXPERIMENTAL, since = "5.12")` to the declaration for both attributes.

2025-01-02 10:45 UTC, marcphilipp commented on documentation/src/test/java/example/ParameterizedTestDemo.java
> +	@EnumSource(mode = EXCLUDE, from = "HOURS", to = "DAYS", names = { "HALF_DAYS" })
I think this is slightly more readable:

```suggestion
	@EnumSource(from = "HOURS", to = "DAYS", mode = EXCLUDE, names = { "HALF_DAYS" })
```

2025-01-02 10:45 UTC, marcphilipp commented on junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EnumArgumentsProvider.java
> +			return EnumSet.noneOf(enumClass);
We should validate that both `from` and `to` are empty in this case, shouldn't we?

2025-01-02 15:45 UTC, CharlesLgn commented on documentation/src/test/java/example/ParameterizedTestDemo.java
> +	}
I do not remember why.. so it must not be a good idea

2025-01-02 20:56 UTC, yhkuo41 commented on junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EnumArgumentsProvider.java
> +		return EnumSet.range(from, to);
sure

2025-01-08 09:55 UTC, marcphilipp approved these changes

2025-01-08 10:26 UTC, merged

2025-01-08 10:26 UTC, marcphilipp commented
@yhkuo41 Thank you for your contribution! :+1: